### ISSUE TITLE
Issue - Multiple selected row copy and paste

### ISSUE THREAD

**Issue by precisepumpkinnose** [Cjreek/D2ExcelPlus#7]
Trying so select the rows MonuMin(H) Row 3 to MonuMax(H) Row 8 to MonuMin(N) Row 3 results in copying the values to MonuMin(H) Row 3 to MonuMax(H) Row 8 correctly but at the same time deleting MonuMin(H) Row 3 to MonuMin(H) Row 8. I have attached pictures before and after copy and paste 

BEFORE:

![before](https://user-images.githubusercontent.com/100239247/155219301-5b166eb5-2af5-4507-85d4-0aada2e00212.PNG)

 AFTER: values copied, but rows empty

![after](https://user-images.githubusercontent.com/100239247/155219509-146c5998-a062-4439-9c5c-424c600ea240.PNG)

**Comment by Cjreek** [comment]
Are you using the latest release? https://github.com/Cjreek/D2ExcelPlus/releases/tag/D2EP092
That bug should be fixed in 0.92

**Comment by starlove7** [comment]
In version 0.92, when copying and pasting multiple cells, the adjacent cells still contain empty values.

**Comment by enders-blade** [comment]
This issue still exists in .92.  If you try to copy an entire column and paste it in another column, it blanks out the column next to it.
